компонент CounterButton
js-tasks-ru/vue-20200615_aleksey488 pull request #2
Opened 2020-07-06 10:55 UTC by m48bnt

2020-07-06 11:00 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-07-06 12:54 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-07-06 12:59 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-07-06 14:47 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-07-06 14:56 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-07-07 14:04 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
MeetupPage
+ MeetupCover должен иметь необязательные строковые пропсы link и title
+ MeetupCover должен рендерить изображение митапа
+ MeetupCover должен корректно обрабатывать отсутствие ссылки на изображение
+ MeetupCover должен рендерить название митапа
+ MeetupDescription должен иметь необязательный строковый пропс description
+ MeetupDescription должен рендерить описание митапа
+ MeetupInfo должен иметь обязательный пропс meetup
+ MeetupInfo должен рендерить краткое описание митапа
+ MeetupAgendaItem должен иметь обязательный пропс agendaItem
+ MeetupAgendaItem должен показывать время
+ MeetupAgendaItem должен показывать заголовок по умолчанию
+ MeetupAgendaItem должен показывать иконку регистрации
+ MeetupAgendaItem должен показывать доклад
+ MeetupAgenda должен иметь пропс agenda
+ MeetupAgenda должен выводить программу
+ MeetupView должен иметь пропс meetup
+ MeetupView должен показывать изображение, описание информацию и программу
+ MeetupPage должен быть определён
```
```diff
MeetupsCalendar
+ MeetupsCalendar должен иметь обязательный пропс meetups по списком митапов
+ MeetupsCalendar должен вывести 5 строк по 7 недель для апреля 2020
+ MeetupsCalendar должен вывести только первые два и последние три дня для апреля 2020 неактивными
+ MeetupsCalendar должен вывести правильные числа для апреля 2020
+ MeetupsCalendar должен локализовано месяц и год в заголовке для апреля 2020
+ MeetupsCalendar должен вывести май 2020
+ MeetupsCalendar должен вывести июнь 2020
+ MeetupsCalendar должен показать февраль 2021 после 10 кликов на след. месяц с апреля 2020
+ MeetupsCalendar должен показать февраль 2021 после 9 кликов на след. месяц с 31 мая 2020
+ MeetupsCalendar должен показать ноябрь 2019 после 5 кликов на пред. месяц с апреля 2020
+ MeetupsCalendar должен показать митапы 12 мая после перехода на следующий месяц с апреля 2020
```
```diff
Компонент CounterButton
+ Компонент должен рендерить кнопку с текстом count
+ Компонент должен иметь count 0 по умолчанию
+ Компонент должен увеличивать значение на 1 по клику
+ Пропс count должен иметь числовой тип
```
```diff
CounterButton
+ Задача добавлена, но требует ручной проверки
```
```diff
Meetup Page Draft
+ Задача добавлена, но требует ручной проверки
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-07-07 14:52 UTC, ShGKme requested changes
Задача 2-1 принята!
Задача 2-3 принята! Хотя не самое эффективное решение (для каждого дня месяца каждый раз смене месяца происходит поиск по всему списку митапов; можно один раз пройтись по списку митапов и сразу добавить каждый митап в нужный день). 
В задаче 2-2 есть существенный недочёт.

2020-07-07 14:52 UTC, ShGKme commented on 2-module/2-task/MeetupAgendaItem.js
> +        <h5 class="meetup-agenda__title" v-html=" processedAgenda.title"></h5>
v-html выведет значение как html без какого-либо экранирования. Это потенциальный XSS.

Любой пользователь может сделать свой митап с любым заголовком, в том числе использовать там теги или внедрять скрипты. С v-html получится серьёзная дыра в безопасности.

Правильнее использовать обычные выражения `{{ value }}`.

если так было сделано из-за `<s>` в названии одного из докладов, то это оригинальное название: [https://vueconf.us/schedule/](https://vueconf.us/schedule/)

`All you need is <s>love</s> Apollo Client`

*Эту проблему потребуется исправить, чтобы задача была зачтена.*

2020-07-07 14:52 UTC, ShGKme commented on 2-module/2-task/MeetupDescription.js
> +      default: () => '',
Для имутабельных типов можно указывать значение, а не функцию. Функция нужна при использовании мутабельных типов (объект, массив), чтобы не было ссылки на один объект в нескольких компонентах.

2020-07-08 06:29 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
MeetupPage
+ MeetupCover должен иметь необязательные строковые пропсы link и title
+ MeetupCover должен рендерить изображение митапа
+ MeetupCover должен корректно обрабатывать отсутствие ссылки на изображение
+ MeetupCover должен рендерить название митапа
+ MeetupDescription должен иметь необязательный строковый пропс description
+ MeetupDescription должен рендерить описание митапа
+ MeetupInfo должен иметь обязательный пропс meetup
+ MeetupInfo должен рендерить краткое описание митапа
+ MeetupAgendaItem должен иметь обязательный пропс agendaItem
+ MeetupAgendaItem должен показывать время
+ MeetupAgendaItem должен показывать заголовок по умолчанию
+ MeetupAgendaItem должен показывать иконку регистрации
+ MeetupAgendaItem должен показывать доклад
+ MeetupAgenda должен иметь пропс agenda
+ MeetupAgenda должен выводить программу
+ MeetupView должен иметь пропс meetup
+ MeetupView должен показывать изображение, описание информацию и программу
+ MeetupPage должен быть определён
```
```diff
MeetupsCalendar
+ MeetupsCalendar должен иметь обязательный пропс meetups по списком митапов
+ MeetupsCalendar должен вывести 5 строк по 7 недель для апреля 2020
+ MeetupsCalendar должен вывести только первые два и последние три дня для апреля 2020 неактивными
+ MeetupsCalendar должен вывести правильные числа для апреля 2020
+ MeetupsCalendar должен локализовано месяц и год в заголовке для апреля 2020
+ MeetupsCalendar должен вывести май 2020
+ MeetupsCalendar должен вывести июнь 2020
+ MeetupsCalendar должен показать февраль 2021 после 10 кликов на след. месяц с апреля 2020
+ MeetupsCalendar должен показать февраль 2021 после 9 кликов на след. месяц с 31 мая 2020
+ MeetupsCalendar должен показать ноябрь 2019 после 5 кликов на пред. месяц с апреля 2020
+ MeetupsCalendar должен показать митапы 12 мая после перехода на следующий месяц с апреля 2020
```
```diff
DropdownButton
+ Должен быть класс dropdown__item_icon и иконка в варианте с иконкой
- Компонент должен иметь параметры title, options, value
- Кнопка должна иметь текст с заголовком из параметра
- Кнопка должна иметь текст с заголовком и выбранным вариантом
- Компонент должен реагировать на изменение выбранного варианта
- Компонент должен показывать список скрытым, открывать его по клику и закрывать по повторному клику
- Выбор вариант порождает событие change
- Список должен скрываться после выбора вари��нта
- Должен быть класс dropdown__toggle_icon и иконка на кнопке выбранного варианта при наличии icon в списке вариантов
```
```diff
AppToast
- Компонент изначально не показывает ни одного тоста
- Компонент должен рендерить success тост с сообщением
- Компонент должен рендерить error тост с сообщением
- Компонент должен рендерить список сообщений
- Компонент удалять тост через 5 секунд
```
```diff
FormGroup
- Компонент имеет параметры inline, label
- Компонент должен выводить содержимое в блоке form-group
- Компонент не должен выводить label по умолчанию
- Компонент должен выводить label со значением параметра
- Компонент должен выводить слот после label
```
```diff
CounterButton.vue
- Компонент должен иметь необязательный числовой параметр count со значением 0 по умолчанию
- Компонент должен рендерить кнопку со значением счётчика
- При клике компонент должен порождать событие `increment` с увеличенным на 1 значением счётчика
- Компонент должен выводить новое значение счётчика при его обновлении
```
```diff
Компонент CounterButton
+ Компонент должен рендерить кнопку с текстом count
+ Компонент должен иметь count 0 по умолчанию
+ Компонент должен увеличивать значение на 1 по клику
+ Пропс count должен иметь числовой тип
```
```diff
CounterButton
+ Задача добавлена, но требует ручной проверки
```
```diff
Meetup Page Draft
+ Задача добавлена, но требует ручной проверки
```

2020-07-08 07:35 UTC, ShGKme approved these changes
Задача 3-2 принята! 👍

2020-07-08 07:35 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-07-08 07:36 UTC, ShGKme commented
Не заметил, что добавились новые задачи. PR принимается, когда сданы все добавленные задачи.

2020-07-08 09:36 UTC, jsru commented
@ShGKme ping :)

2020-07-08 15:26 UTC, ShGKme approved these changes
Задачи 3-1, 3-2, 3-3 и 3-4 приняты!
Отлично 👍

2020-07-08 15:26 UTC, merged